sudo: false
matrix:
  fast_finish: true

language: go
go:
  - "1.13.x"

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
  email: false
